### ISSUE TITLE
Installation fails on Ubuntu 22.04 or newer

### ISSUE THREAD

**Issue by thariq-shanavas** [bjornsturmberg/NumBAT#8]
Installation fails on Linux machines running GCC 10 or newer (i.e., Ubuntu 22.04 and newer) due to the issue highlighted here: https://forum.mmm.ucar.edu/threads/how-to-fix-error-rank-mismatch-between-actual-argument-at-1-and-actual-argument-at-2.11998/#post-27521

A quick fix is to set the flags for gfortran in setup.sh - see attached file, line 9.

![Screenshot from 2023-01-01 19-30-22](https://user-images.githubusercontent.com/19273195/210191474-b03a4e99-283d-4fe7-962e-63066646ad3b.png)

**Comment by bjornsturmberg** [comment]
Thank you very much for noting this and finding a fix @thariq-shanavas !
I have implemented your suggestion in the latest commit. 

Please note that the main fork of NumBAT is now at https://github.com/michaeljsteel/NumBAT 
@michaeljsteel you will likely want to implement this fix as well, if you haven't already.
